mkdir countries
mkdir holdings
mkdir holdings_hash
mkdir institutions
mkdir shexmlOutput
mkdir shexmlRules
mkdir terms
mkdir shexmlOutputTerms
mkdir shexmlRulesTerms
mkdir ghettos
mkdir shexmlOutputGhettos
mkdir shexmlRulesGhettos
mkdir camps
mkdir shexmlOutputCamps
mkdir shexmlRulesCamps
mkdir people
mkdir shexmlOutputPeople
mkdir shexmlRulesPeople
mkdir cb
mkdir shexmlOutputCb
mkdir shexmlRulesCb